// <auto-generated />
namespace Wohnungstausch24.Migrations.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Step7Fixes : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Step7Fixes));
        
        string IMigrationMetadata.Id
        {
            get { return "201703081453556_Step7Fixes"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
