namespace Wohnungstausch24.Migrations.Migrations
{
    using System;
    using System.Data.Entity.Migrations;
    
    public partial class SaveChangesMethodChanged : DbMigration
    {
        public override void Up()
        {
            DropForeignKey("dbo.AgencyBranch", "AgencyId", "dbo.Agency");
            DropForeignKey("dbo.Emphasis", "AgencyId", "dbo.Agency");
            DropForeignKey("dbo.Agency", "ManagerId", "dbo.AspNetUsers");
            DropForeignKey("dbo.Organization", "AgencyId", "dbo.Agency");
            DropForeignKey("dbo.Language", "AgentId", "dbo.Agent");
            DropForeignKey("dbo.Agent", "UserId", "dbo.AspNetUsers");
            DropForeignKey("dbo.AspNetUserClaims", "UserId", "dbo.AspNetUsers");
            DropForeignKey("dbo.Listing", "UserId", "dbo.AspNetUsers");
            DropForeignKey("dbo.AspNetUserLogins", "UserId", "dbo.AspNetUsers");
            DropForeignKey("dbo.AspNetUserRoles", "UserId", "dbo.AspNetUsers");
            DropForeignKey("searchProfile.SearchProfileListing", "UserId", "dbo.AspNetUsers");
            DropForeignKey("dbo.UserFile", "UserId", "dbo.AspNetUsers");
            DropForeignKey("dbo.Distance", "ListingId", "dbo.Listing");
            DropForeignKey("dbo.ObjectTextInAnotherLanguage", "ListingId", "dbo.Listing");
            DropForeignKey("dbo.Sight", "ListingId", "dbo.Listing");
            DropForeignKey("dbo.ListingFile", "FileId", "dbo.Wt24File");
            DropForeignKey("dbo.MixedLand", "LandId", "dbo.Listing");
            DropForeignKey("dbo.Balcony", "ResidenceId", "dbo.Listing");
            DropForeignKey("dbo.Bathroom", "ResidenceId", "dbo.Listing");
            DropForeignKey("dbo.Beaconing", "ResidenceId", "dbo.Listing");
            DropForeignKey("dbo.Floor", "ResidenceId", "dbo.Listing");
            DropForeignKey("dbo.Heating", "ResidenceId", "dbo.Listing");
            DropForeignKey("dbo.ParkingSpace", "ResidenceId", "dbo.Listing");
            DropForeignKey("searchProfile.Client", "SearchProfileId", "searchProfile.SearchProfileListing");
            DropForeignKey("searchProfile.SpLocation", "SpListingId", "searchProfile.SearchProfileListing");
            DropForeignKey("searchProfile.Person", "ClientId", "searchProfile.Client");
            DropForeignKey("searchProfile.SpGeoDirection", "SpResidenceId", "searchProfile.SearchProfileListing");
            DropForeignKey("searchProfile.SpBeaconing", "SpResidenceId", "searchProfile.SearchProfileListing");
            DropForeignKey("searchProfile.SpEnergy", "SpResidenceId", "searchProfile.SearchProfileListing");
            DropForeignKey("searchProfile.SpFeatureCategory", "SpResidenceId", "searchProfile.SearchProfileListing");
            DropForeignKey("searchProfile.SpFloor", "SpResidenceId", "searchProfile.SearchProfileListing");
            DropForeignKey("searchProfile.SpHeating", "SpResidenceId", "searchProfile.SearchProfileListing");
            DropForeignKey("searchProfile.SpParkSpace", "SpResidenceId", "searchProfile.SearchProfileListing");
            DropForeignKey("searchProfile.SpRollerBlind", "SpResidenceId", "searchProfile.SearchProfileListing");
            DropForeignKey("searchProfile.SpSight", "SpResidenceId", "searchProfile.SearchProfileListing");
            DropForeignKey("searchProfile.SpFlatType", "SpFlatId", "searchProfile.SearchProfileListing");
            DropForeignKey("searchProfile.SpHouseType", "SpHouseId", "searchProfile.SearchProfileListing");
            DropForeignKey("dbo.LocationLevel1", "ParentId", "dbo.Country");
            DropForeignKey("dbo.LocationLevel2", "ParentId", "dbo.LocationLevel1");
            DropForeignKey("dbo.LocationLevel3", "ParentId", "dbo.LocationLevel2");
            DropForeignKey("dbo.AspNetUserRoles", "RoleId", "dbo.AspNetRoles");
            AddForeignKey("dbo.AgencyBranch", "AgencyId", "dbo.Agency", "Id", cascadeDelete: true);
            AddForeignKey("dbo.Emphasis", "AgencyId", "dbo.Agency", "Id", cascadeDelete: true);
            AddForeignKey("dbo.Agency", "ManagerId", "dbo.AspNetUsers", "Id", cascadeDelete: true);
            AddForeignKey("dbo.Organization", "AgencyId", "dbo.Agency", "Id", cascadeDelete: true);
            AddForeignKey("dbo.Language", "AgentId", "dbo.Agent", "Id", cascadeDelete: true);
            AddForeignKey("dbo.Agent", "UserId", "dbo.AspNetUsers", "Id", cascadeDelete: true);
            AddForeignKey("dbo.AspNetUserClaims", "UserId", "dbo.AspNetUsers", "Id", cascadeDelete: true);
            AddForeignKey("dbo.Listing", "UserId", "dbo.AspNetUsers", "Id", cascadeDelete: true);
            AddForeignKey("dbo.AspNetUserLogins", "UserId", "dbo.AspNetUsers", "Id", cascadeDelete: true);
            AddForeignKey("dbo.AspNetUserRoles", "UserId", "dbo.AspNetUsers", "Id", cascadeDelete: true);
            AddForeignKey("searchProfile.SearchProfileListing", "UserId", "dbo.AspNetUsers", "Id", cascadeDelete: true);
            AddForeignKey("dbo.UserFile", "UserId", "dbo.AspNetUsers", "Id", cascadeDelete: true);
            AddForeignKey("dbo.Distance", "ListingId", "dbo.Listing", "Id", cascadeDelete: true);
            AddForeignKey("dbo.ObjectTextInAnotherLanguage", "ListingId", "dbo.Listing", "Id", cascadeDelete: true);
            AddForeignKey("dbo.Sight", "ListingId", "dbo.Listing", "Id", cascadeDelete: true);
            AddForeignKey("dbo.ListingFile", "FileId", "dbo.Wt24File", "Id", cascadeDelete: true);
            AddForeignKey("dbo.MixedLand", "LandId", "dbo.Listing", "Id", cascadeDelete: true);
            AddForeignKey("dbo.Balcony", "ResidenceId", "dbo.Listing", "Id", cascadeDelete: true);
            AddForeignKey("dbo.Bathroom", "ResidenceId", "dbo.Listing", "Id", cascadeDelete: true);
            AddForeignKey("dbo.Beaconing", "ResidenceId", "dbo.Listing", "Id", cascadeDelete: true);
            AddForeignKey("dbo.Floor", "ResidenceId", "dbo.Listing", "Id", cascadeDelete: true);
            AddForeignKey("dbo.Heating", "ResidenceId", "dbo.Listing", "Id", cascadeDelete: true);
            AddForeignKey("dbo.ParkingSpace", "ResidenceId", "dbo.Listing", "Id", cascadeDelete: true);
            AddForeignKey("searchProfile.Client", "SearchProfileId", "searchProfile.SearchProfileListing", "Id", cascadeDelete: true);
            AddForeignKey("searchProfile.SpLocation", "SpListingId", "searchProfile.SearchProfileListing", "Id", cascadeDelete: true);
            AddForeignKey("searchProfile.Person", "ClientId", "searchProfile.Client", "Id", cascadeDelete: true);
            AddForeignKey("searchProfile.SpGeoDirection", "SpResidenceId", "searchProfile.SearchProfileListing", "Id", cascadeDelete: true);
            AddForeignKey("searchProfile.SpBeaconing", "SpResidenceId", "searchProfile.SearchProfileListing", "Id", cascadeDelete: true);
            AddForeignKey("searchProfile.SpEnergy", "SpResidenceId", "searchProfile.SearchProfileListing", "Id", cascadeDelete: true);
            AddForeignKey("searchProfile.SpFeatureCategory", "SpResidenceId", "searchProfile.SearchProfileListing", "Id", cascadeDelete: true);
            AddForeignKey("searchProfile.SpFloor", "SpResidenceId", "searchProfile.SearchProfileListing", "Id", cascadeDelete: true);
            AddForeignKey("searchProfile.SpHeating", "SpResidenceId", "searchProfile.SearchProfileListing", "Id", cascadeDelete: true);
            AddForeignKey("searchProfile.SpParkSpace", "SpResidenceId", "searchProfile.SearchProfileListing", "Id", cascadeDelete: true);
            AddForeignKey("searchProfile.SpRollerBlind", "SpResidenceId", "searchProfile.SearchProfileListing", "Id", cascadeDelete: true);
            AddForeignKey("searchProfile.SpSight", "SpResidenceId", "searchProfile.SearchProfileListing", "Id", cascadeDelete: true);
            AddForeignKey("searchProfile.SpFlatType", "SpFlatId", "searchProfile.SearchProfileListing", "Id", cascadeDelete: true);
            AddForeignKey("searchProfile.SpHouseType", "SpHouseId", "searchProfile.SearchProfileListing", "Id", cascadeDelete: true);
            AddForeignKey("dbo.LocationLevel1", "ParentId", "dbo.Country", "Id", cascadeDelete: true);
            AddForeignKey("dbo.LocationLevel2", "ParentId", "dbo.LocationLevel1", "Id", cascadeDelete: true);
            AddForeignKey("dbo.LocationLevel3", "ParentId", "dbo.LocationLevel2", "Id", cascadeDelete: true);
            AddForeignKey("dbo.AspNetUserRoles", "RoleId", "dbo.AspNetRoles", "Id", cascadeDelete: true);
        }
        
        public override void Down()
        {
            DropForeignKey("dbo.AspNetUserRoles", "RoleId", "dbo.AspNetRoles");
            DropForeignKey("dbo.LocationLevel3", "ParentId", "dbo.LocationLevel2");
            DropForeignKey("dbo.LocationLevel2", "ParentId", "dbo.LocationLevel1");
            DropForeignKey("dbo.LocationLevel1", "ParentId", "dbo.Country");
            DropForeignKey("searchProfile.SpHouseType", "SpHouseId", "searchProfile.SearchProfileListing");
            DropForeignKey("searchProfile.SpFlatType", "SpFlatId", "searchProfile.SearchProfileListing");
            DropForeignKey("searchProfile.SpSight", "SpResidenceId", "searchProfile.SearchProfileListing");
            DropForeignKey("searchProfile.SpRollerBlind", "SpResidenceId", "searchProfile.SearchProfileListing");
            DropForeignKey("searchProfile.SpParkSpace", "SpResidenceId", "searchProfile.SearchProfileListing");
            DropForeignKey("searchProfile.SpHeating", "SpResidenceId", "searchProfile.SearchProfileListing");
            DropForeignKey("searchProfile.SpFloor", "SpResidenceId", "searchProfile.SearchProfileListing");
            DropForeignKey("searchProfile.SpFeatureCategory", "SpResidenceId", "searchProfile.SearchProfileListing");
            DropForeignKey("searchProfile.SpEnergy", "SpResidenceId", "searchProfile.SearchProfileListing");
            DropForeignKey("searchProfile.SpBeaconing", "SpResidenceId", "searchProfile.SearchProfileListing");
            DropForeignKey("searchProfile.SpGeoDirection", "SpResidenceId", "searchProfile.SearchProfileListing");
            DropForeignKey("searchProfile.Person", "ClientId", "searchProfile.Client");
            DropForeignKey("searchProfile.SpLocation", "SpListingId", "searchProfile.SearchProfileListing");
            DropForeignKey("searchProfile.Client", "SearchProfileId", "searchProfile.SearchProfileListing");
            DropForeignKey("dbo.ParkingSpace", "ResidenceId", "dbo.Listing");
            DropForeignKey("dbo.Heating", "ResidenceId", "dbo.Listing");
            DropForeignKey("dbo.Floor", "ResidenceId", "dbo.Listing");
            DropForeignKey("dbo.Beaconing", "ResidenceId", "dbo.Listing");
            DropForeignKey("dbo.Bathroom", "ResidenceId", "dbo.Listing");
            DropForeignKey("dbo.Balcony", "ResidenceId", "dbo.Listing");
            DropForeignKey("dbo.MixedLand", "LandId", "dbo.Listing");
            DropForeignKey("dbo.ListingFile", "FileId", "dbo.Wt24File");
            DropForeignKey("dbo.Sight", "ListingId", "dbo.Listing");
            DropForeignKey("dbo.ObjectTextInAnotherLanguage", "ListingId", "dbo.Listing");
            DropForeignKey("dbo.Distance", "ListingId", "dbo.Listing");
            DropForeignKey("dbo.UserFile", "UserId", "dbo.AspNetUsers");
            DropForeignKey("searchProfile.SearchProfileListing", "UserId", "dbo.AspNetUsers");
            DropForeignKey("dbo.AspNetUserRoles", "UserId", "dbo.AspNetUsers");
            DropForeignKey("dbo.AspNetUserLogins", "UserId", "dbo.AspNetUsers");
            DropForeignKey("dbo.Listing", "UserId", "dbo.AspNetUsers");
            DropForeignKey("dbo.AspNetUserClaims", "UserId", "dbo.AspNetUsers");
            DropForeignKey("dbo.Agent", "UserId", "dbo.AspNetUsers");
            DropForeignKey("dbo.Language", "AgentId", "dbo.Agent");
            DropForeignKey("dbo.Organization", "AgencyId", "dbo.Agency");
            DropForeignKey("dbo.Agency", "ManagerId", "dbo.AspNetUsers");
            DropForeignKey("dbo.Emphasis", "AgencyId", "dbo.Agency");
            DropForeignKey("dbo.AgencyBranch", "AgencyId", "dbo.Agency");
            AddForeignKey("dbo.AspNetUserRoles", "RoleId", "dbo.AspNetRoles", "Id");
            AddForeignKey("dbo.LocationLevel3", "ParentId", "dbo.LocationLevel2", "Id");
            AddForeignKey("dbo.LocationLevel2", "ParentId", "dbo.LocationLevel1", "Id");
            AddForeignKey("dbo.LocationLevel1", "ParentId", "dbo.Country", "Id");
            AddForeignKey("searchProfile.SpHouseType", "SpHouseId", "searchProfile.SearchProfileListing", "Id");
            AddForeignKey("searchProfile.SpFlatType", "SpFlatId", "searchProfile.SearchProfileListing", "Id");
            AddForeignKey("searchProfile.SpSight", "SpResidenceId", "searchProfile.SearchProfileListing", "Id");
            AddForeignKey("searchProfile.SpRollerBlind", "SpResidenceId", "searchProfile.SearchProfileListing", "Id");
            AddForeignKey("searchProfile.SpParkSpace", "SpResidenceId", "searchProfile.SearchProfileListing", "Id");
            AddForeignKey("searchProfile.SpHeating", "SpResidenceId", "searchProfile.SearchProfileListing", "Id");
            AddForeignKey("searchProfile.SpFloor", "SpResidenceId", "searchProfile.SearchProfileListing", "Id");
            AddForeignKey("searchProfile.SpFeatureCategory", "SpResidenceId", "searchProfile.SearchProfileListing", "Id");
            AddForeignKey("searchProfile.SpEnergy", "SpResidenceId", "searchProfile.SearchProfileListing", "Id");
            AddForeignKey("searchProfile.SpBeaconing", "SpResidenceId", "searchProfile.SearchProfileListing", "Id");
            AddForeignKey("searchProfile.SpGeoDirection", "SpResidenceId", "searchProfile.SearchProfileListing", "Id");
            AddForeignKey("searchProfile.Person", "ClientId", "searchProfile.Client", "Id");
            AddForeignKey("searchProfile.SpLocation", "SpListingId", "searchProfile.SearchProfileListing", "Id");
            AddForeignKey("searchProfile.Client", "SearchProfileId", "searchProfile.SearchProfileListing", "Id");
            AddForeignKey("dbo.ParkingSpace", "ResidenceId", "dbo.Listing", "Id");
            AddForeignKey("dbo.Heating", "ResidenceId", "dbo.Listing", "Id");
            AddForeignKey("dbo.Floor", "ResidenceId", "dbo.Listing", "Id");
            AddForeignKey("dbo.Beaconing", "ResidenceId", "dbo.Listing", "Id");
            AddForeignKey("dbo.Bathroom", "ResidenceId", "dbo.Listing", "Id");
            AddForeignKey("dbo.Balcony", "ResidenceId", "dbo.Listing", "Id");
            AddForeignKey("dbo.MixedLand", "LandId", "dbo.Listing", "Id");
            AddForeignKey("dbo.ListingFile", "FileId", "dbo.Wt24File", "Id");
            AddForeignKey("dbo.Sight", "ListingId", "dbo.Listing", "Id");
            AddForeignKey("dbo.ObjectTextInAnotherLanguage", "ListingId", "dbo.Listing", "Id");
            AddForeignKey("dbo.Distance", "ListingId", "dbo.Listing", "Id");
            AddForeignKey("dbo.UserFile", "UserId", "dbo.AspNetUsers", "Id");
            AddForeignKey("searchProfile.SearchProfileListing", "UserId", "dbo.AspNetUsers", "Id");
            AddForeignKey("dbo.AspNetUserRoles", "UserId", "dbo.AspNetUsers", "Id");
            AddForeignKey("dbo.AspNetUserLogins", "UserId", "dbo.AspNetUsers", "Id");
            AddForeignKey("dbo.Listing", "UserId", "dbo.AspNetUsers", "Id");
            AddForeignKey("dbo.AspNetUserClaims", "UserId", "dbo.AspNetUsers", "Id");
            AddForeignKey("dbo.Agent", "UserId", "dbo.AspNetUsers", "Id");
            AddForeignKey("dbo.Language", "AgentId", "dbo.Agent", "Id");
            AddForeignKey("dbo.Organization", "AgencyId", "dbo.Agency", "Id");
            AddForeignKey("dbo.Agency", "ManagerId", "dbo.AspNetUsers", "Id");
            AddForeignKey("dbo.Emphasis", "AgencyId", "dbo.Agency", "Id");
            AddForeignKey("dbo.AgencyBranch", "AgencyId", "dbo.Agency", "Id");
        }
    }
}
